include: package:very_good_analysis/analysis_options.6.0.0.yaml
analyzer:
  errors:
    one_member_abstracts: ignore
    invalid_annotation_target: ignore
    unused_local_variable: ignore
    unused_field: ignore
    must_be_immutable: ignore
  exclude:
    - "**.g.dart"
    - "**.gr.dart"
    - "**.freezed.dart"
    - "**.config.dart"
    - "**.mocks.dart"
linter:
  rules:
    sort_pub_dependencies: true
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    require_trailing_commas: false
    always_use_package_imports: true
    avoid_relative_lib_imports: true
    
    
    
    
    
    
    
    