# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Android new version"
  gradle(
      task: 'assemble',
      build_type: 'Release'
  )
  lane :android_firebase_distribution_dev do
    firebase_app_distribution(
        app: "1:293746:android:293746",
        groups: "android---dev",
        release_notes: "",
        firebase_cli_path: "/usr/local/bin/firebase",
        apk_path: "../build/app/outputs/apk/release/app-release.apk",
        
    )
end
  lane :android_firebase_distribution_test do
      firebase_app_distribution(
          app: "1:293746:android:293746293746",
          groups: "android---test",
          release_notes: "TEST",
          firebase_cli_path: "/usr/local/bin/firebase",
          apk_path: "../build/app/outputs/apk/release/app-release.apk"
      )
  end
  lane :android_firebase_distribution_uat do
    firebase_app_distribution(
        app: "1:293746:android:293746",
        groups: "android---uat",
        release_notes: "",
        firebase_cli_path: "/usr/local/bin/firebase",
        apk_path: "../build/app/outputs/apk/release/app-release.apk"
    )
end
  lane :android_firebase_distribution_prod do
    firebase_app_distribution(
        app: "1:293746:android:293746",
        groups: "android---prod",
        release_notes: "PROD",
        firebase_cli_path: "/usr/local/bin/firebase",
        apk_path: "../build/app/outputs/apk/release/app-release.apk"
    )
  end
end
